
export const EVENT_TODO_NEW_ITEM       = 'EVENT_TODO_NEW_ITEM';
export const EVENT_TODO_LIST_COUNTS    = 'EVENT_TODO_LIST_COUNTS';
export const EVENT_TODO_COMPLETED_ITEM = 'EVENT_TODO_COMPLETED_ITEM';
export const EVENT_TODO_DELETEED_ITEM  = 'EVENT_TODO_DELETEED_ITEM';