
export const EVENT_TODOMVC_NEW_ITEM          = 'EVENT_TODOMVC_NEW_ITEM';
export const EVENT_TODOMVC_LIST_COUNTS       = 'EVENT_TODOMVC_LIST_COUNTS';
export const EVENT_TODOMVC_COMPLETED_CURRENT = 'EVENT_TODOMVC_COMPLETED_CURRENT';
export const EVENT_TODOMVC_DELETE_CURRENT    = 'EVENT_TODOMVC_DELETE_CURRENT';